import { Activity, Excursion, TransportRoute, Review } from '@/types'

// ─── ACTIVITIES ───────────────────────────────────────────────────────────────
export const activities: Activity[] = [
  {
    id: 'act-1',
    title: 'Camel Ride in the Palmeraie',
    slug: 'camel-ride',
    description: 'Glide through the golden Palmeraie of Marrakech on the back of a camel — a timeless Moroccan experience. Our professional guides lead you through ancient palm groves as the sun sets over the Atlas Mountains, painting the sky in shades of crimson and amber. This is more than just a ride — it\'s a journey back in time to the ancient caravan routes of the Sahara.',
    short_description: 'A timeless journey through Marrakech\'s golden Palmeraie on camelback at sunset.',
    category: 'activity',
    price: null,
    price_label: 'From €25 / person',
    duration: '1–2 hours',
    cover_image_url: '/images/activities/camel-ride.jpg',
    gallery: [
      '/images/activities/camel-ride-g1.jpg',
      '/images/activities/camel-ride-g2.png',
    ],
    featured: true,
    order_rank: 1,
    highlights: ['Sunset golden hour ride', 'Professional Berber guides', 'Palm grove scenery', 'Photo opportunities', 'Small groups (max 8)'],
    included: ['Guide', 'Safety equipment', 'Water', 'Photos'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'act-2',
    title: 'Quad Biking in the Desert',
    slug: 'quad-biking',
    description: 'Feel the thrill of speeding across the Agafay Desert and Palmeraie on a powerful quad bike. Our guided tours take you off the beaten track, through rugged terrain and breathtaking landscapes just outside Marrakech. Whether you\'re a beginner or experienced rider, our guides ensure a safe and exhilarating adventure.',
    short_description: 'Race across desert dunes and palm groves on a powerful quad bike.',
    category: 'activity',
    price: null,
    price_label: 'From €35 / person',
    duration: '2–3 hours',
    cover_image_url: '/images/activities/quad-biking.jpg',
    gallery: [
      '/images/activities/quad-biking-g1.jpg',
      '/images/activities/quad-biking-g2.png',
    ],
    featured: true,
    order_rank: 2,
    highlights: ['Desert & Palmeraie routes', 'All skill levels welcome', 'Safety briefing included', 'Helmet & gear provided', 'GoPro footage available'],
    included: ['Quad bike', 'Helmet & goggles', 'Guide', 'Insurance'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'act-3',
    title: 'Hot Air Balloon over Marrakech',
    slug: 'hot-air-balloon',
    description: 'Rise above the medina at dawn and witness Morocco from a perspective few ever see. As the sun climbs over the Atlas Mountains, you\'ll float silently over ochre kasbahs, emerald palm groves, and the ancient city below. This is the most magical way to experience Marrakech — peaceful, breathtaking, and unforgettable.',
    short_description: 'Soar at dawn over Marrakech\'s medina with Atlas Mountain views.',
    category: 'activity',
    price: null,
    price_label: 'From €150 / person',
    duration: '3–4 hours (1hr flight)',
    cover_image_url: '/images/activities/hot-air-balloon.jpg',
    gallery: [
      '/images/activities/hot-air-balloon-g1.jpg',
      '/images/activities/hot-air-balloon-g2.png',
    ],
    featured: true,
    order_rank: 3,
    highlights: ['Sunrise departure', 'Atlas Mountain panoramas', 'Champagne landing toast', 'Certificate of flight', 'Hotel pickup included'],
    included: ['Hotel transfer', 'Balloon flight', 'Berber breakfast', 'Certificate'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'act-4',
    title: 'Electric Cycle Bike Tour',
    slug: 'cycle-bike',
    description: 'Explore Marrakech\'s hidden neighborhoods, gardens, and souks at your own pace on an electric bike. Our guided tours wind through the Mellah (Jewish Quarter), past the Koutoubia Mosque, through fragrant gardens, and into corners of the medina most tourists never discover.',
    short_description: 'Discover Marrakech\'s hidden gems on a guided electric bike tour.',
    category: 'activity',
    price: null,
    price_label: 'From €30 / person',
    duration: '3 hours',
    cover_image_url: '/images/activities/cycle-bike.jpg',
    gallery: [
      '/images/activities/cycle-bike-g1.jpg',
      '/images/activities/cycle-bike-g2.png',
    ],
    featured: false,
    order_rank: 4,
    highlights: ['E-bike — no fitness required', 'Hidden medina streets', 'Secret gardens', 'Local guide stories', 'Small groups'],
    included: ['E-bike rental', 'Helmet', 'Guide', 'Mint tea stop'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'act-5',
    title: 'Sidecar Tour of Marrakech',
    slug: 'side-car',
    description: 'Hop into a vintage sidecar motorcycle and let your guide chauffeur you through the best of Marrakech. It\'s retro, it\'s fun, and it\'s the most stylish way to see the city — from the chaos of Jemaa el-Fna to the tranquil gardens of the Agdal, all in classic style.',
    short_description: 'Ride through Marrakech in a retro vintage sidecar motorcycle.',
    category: 'activity',
    price: null,
    price_label: 'From €45 / person',
    duration: '2 hours',
    cover_image_url: '/images/activities/side-car.jpg',
    gallery: [
      '/images/activities/side-car-g1.jpg',
      '/images/activities/side-car-g2.png',
    ],
    featured: false,
    order_rank: 5,
    highlights: ['Vintage 1960s sidecars', 'Iconic city landmarks', 'Flexible routes', 'Photo stops', 'Couples & family friendly'],
    included: ['Sidecar ride', 'Helmet', 'Driver-guide', 'Tea stop'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'act-6',
    title: 'Traditional Hammam & Spa',
    slug: 'hammam-spa',
    description: 'Surrender to centuries of Moroccan bathing tradition in a authentic hammam. Skilled practitioners use black savon beldi soap and kessa gloves to cleanse and exfoliate, followed by a nourishing argan oil massage. Leave feeling reborn — silky smooth skin, total relaxation, and a deep connection to Moroccan culture.',
    short_description: 'Experience centuries-old Moroccan bathing rituals in an authentic hammam.',
    category: 'activity',
    price: null,
    price_label: 'From €40 / person',
    duration: '1.5–2 hours',
    cover_image_url: '/images/activities/hammam-spa.jpg',
    gallery: [
      '/images/activities/hammam-spa-g1.jpg',
      '/images/activities/hammam-spa-g2.png',
    ],
    featured: true,
    order_rank: 6,
    highlights: ['Traditional black soap ritual', 'Kessa exfoliation', 'Argan oil massage', 'Private or shared hammam', 'Couples packages available'],
    included: ['Hammam towel & kit', 'Black soap', 'Argan oil treatment', 'Mint tea'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'act-7',
    title: 'Moroccan Cooking Class',
    slug: 'cooking-class',
    description: 'Learn the art of Moroccan cuisine in a traditional riad kitchen. Start with a guided tour of the Djemaa el-Fna spice market to hand-pick your ingredients, then return to the cooking studio to master iconic dishes: fragrant tagine, fluffy couscous, flaky bastilla, and freshly baked msemen. Take the recipes home and recreate Morocco in your own kitchen.',
    short_description: 'Master tagine, couscous & more in a traditional riad kitchen.',
    category: 'activity',
    price: null,
    price_label: 'From €55 / person',
    duration: '4–5 hours',
    cover_image_url: '/images/activities/cooking-class.jpg',
    gallery: [
      '/images/activities/cooking-class-g1.jpg',
      '/images/activities/cooking-class-g2.png',
    ],
    featured: false,
    order_rank: 7,
    highlights: ['Spice market visit', 'Hands-on cooking', '3-course Moroccan meal', 'Recipe booklet to take home', 'Vegetarian options available'],
    included: ['Market tour', 'All ingredients', 'Cooking instruction', 'Lunch', 'Recipe booklet'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'act-8',
    title: 'Paragliding over the Atlas',
    slug: 'paragliding',
    description: 'Soar like an eagle over the dramatic Atlas Mountain foothills in a tandem paragliding flight with an experienced instructor. Launch from the Agafay plateau and ride thermal currents above golden desert plains, emerald valleys, and snow-capped peaks. No experience needed — just a sense of adventure.',
    short_description: 'Tandem paragliding over Atlas foothills — no experience required.',
    category: 'activity',
    price: null,
    price_label: 'From €80 / person',
    duration: '2–3 hours (20–30 min flight)',
    cover_image_url: '/images/activities/paragliding.jpg',
    gallery: [
      '/images/activities/paragliding-g1.jpg',
      '/images/activities/paragliding-g2.png',
    ],
    featured: false,
    order_rank: 8,
    highlights: ['Certified instructors', 'Atlas Mountain views', 'Tandem — no experience needed', 'GoPro video included', 'Hotel transfer available'],
    included: ['Equipment', 'Certified instructor', 'Transfer from Marrakech', 'Video footage'],
    created_at: '2024-01-01T00:00:00Z',
  },
]

// ─── EXCURSIONS ───────────────────────────────────────────────────────────────
export const excursions: Excursion[] = [
  {
    id: 'exc-1',
    title: 'Ourika Valley & 3 Valleys',
    slug: 'ourika-valley',
    description: 'Just 30km from Marrakech, the Ourika Valley feels like another world. Lush terraced gardens cling to Atlas hillsides, Berber villages dot the valley floor, and the Ourika River rushes below. Visit the famous Setti Fatma waterfalls, explore local Berber homes, and taste freshly made tagine in a riverside restaurant.',
    short_description: 'Lush Atlas foothills, waterfalls & authentic Berber villages — 30km from Marrakech.',
    category: 'excursion',
    price: null,
    price_label: 'From €30 / person',
    duration: 'Full day (8–10 hrs)',
    cover_image_url: '/images/activities/ourika-valley.jpg',
    gallery: [
      '/images/activities/ourika-valley-g1.jpg',
      '/images/activities/ourika-valley-g2.png',
    ],
    featured: true,
    order_rank: 1,
    highlights: ['Setti Fatma waterfalls', 'Berber village visit', 'Local market (Mondays)', 'Atlas Mountain scenery', 'Riverside tagine lunch'],
    included: ['Transport', 'Guide', 'Lunch', 'Water'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'exc-2',
    title: 'Essaouira — The Windy City',
    slug: 'essaouira',
    description: 'Step into the bohemian blue-and-white port city of Essaouira, a UNESCO World Heritage medina perched on the Atlantic coast. Wander ramparts where cannons face the crashing sea, browse argan cooperative workshops, taste fresh grilled fish on the harbour, and feel the legendary trade winds in your hair.',
    short_description: 'Atlantic coast UNESCO medina with ramparts, artisan workshops & fresh seafood.',
    category: 'excursion',
    price: null,
    price_label: 'From €35 / person',
    duration: 'Full day (12 hrs)',
    cover_image_url: '/images/activities/essaouira.jpg',
    gallery: [
      '/images/activities/essaouira-g1.jpg',
      '/images/activities/essaouira-g2.png',
    ],
    featured: true,
    order_rank: 2,
    highlights: ['UNESCO World Heritage medina', 'Atlantic ocean ramparts', 'Argan oil cooperative', 'Fresh harbour seafood', 'Gnawa music streets'],
    included: ['Transport', 'Guide', 'Free time to explore'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'exc-3',
    title: 'Ouzoud Waterfalls',
    slug: 'ouzoud-waterfalls',
    description: 'The most spectacular waterfalls in Morocco plunge 110 metres into a rainbow-misted gorge surrounded by ancient olive trees. Take a boat ride through the spray, spot wild Barbary macaques swinging through the trees, and swim in the natural pools below the falls. A stunning natural escape just 3 hours from Marrakech.',
    short_description: 'Morocco\'s highest waterfalls — 110m drop, wild monkeys & natural swimming pools.',
    category: 'excursion',
    price: null,
    price_label: 'From €30 / person',
    duration: 'Full day (12 hrs)',
    cover_image_url: '/images/activities/ouzoud-waterfalls.jpg',
    gallery: [
      '/images/activities/ouzoud-waterfalls-g1.jpg',
      '/images/activities/ouzoud-waterfalls-g2.png',
    ],
    featured: true,
    order_rank: 3,
    highlights: ['110m waterfall drop', 'Wild Barbary macaques', 'Boat ride in the mist', 'Natural swimming pools', 'Olive grove walks'],
    included: ['Transport', 'Guide', 'Boat ride'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'exc-4',
    title: 'Atlas & Ouarzazate — Valley of Roses',
    slug: 'atlas-ouarzazate',
    description: 'Cross the High Atlas via the spectacular Tizi n\'Tichka pass (2260m) and descend into the kasbahs of Ouarzazate — the "Hollywood of Africa." Visit the Aït Benhaddou UNESCO kasbah, the Draa Valley, and the Valley of Roses in Kelaat M\'gouna. An epic journey through Morocco\'s most cinematic landscapes.',
    short_description: 'Cross the High Atlas to Hollywood kasbahs, UNESCO sites & the Valley of Roses.',
    category: 'excursion',
    price: null,
    price_label: 'From €45 / person',
    duration: 'Full day (14 hrs)',
    cover_image_url: '/images/activities/atlas-ouarzazate.jpg',
    gallery: [
      '/images/activities/atlas-ouarzazate-g1.jpg',
      '/images/activities/atlas-ouarzazate-g2.png',
    ],
    featured: true,
    order_rank: 4,
    highlights: ['Tizi n\'Tichka mountain pass', 'Aït Benhaddou UNESCO kasbah', 'Ouarzazate film studios', 'Valley of Roses', 'Draa Valley palmeraie'],
    included: ['Transport', 'Guide', 'Kasbah entrance fees'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'exc-5',
    title: 'Agafay Desert — Stone Desert',
    slug: 'agafay-desert',
    description: 'Just 40 minutes from Marrakech, the Agafay Desert is a lunar landscape of rocky plateaus and dried lake beds with Atlas Mountain panoramas. Perfect for quad biking, camel rides, sunset yoga, or a magical glamping dinner under the Milky Way. The closest desert experience to the city.',
    short_description: 'Lunar stone desert 40 min from Marrakech — quads, camels & Milky Way dinners.',
    category: 'excursion',
    price: null,
    price_label: 'From €40 / person',
    duration: 'Half or full day',
    cover_image_url: '/images/activities/agafay-desert.jpg',
    gallery: [
      '/images/activities/agafay-desert-g1.jpg',
      '/images/activities/agafay-desert-g2.png',
    ],
    featured: false,
    order_rank: 5,
    highlights: ['Atlas Mountain panoramas', 'Quad bikes & camels', 'Luxury desert camps', 'Sunset cocktails', 'Stargazing dinners'],
    included: ['Transport', 'Guide', 'Activity of choice'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'exc-6',
    title: 'Imlil & Toubkal Foothills',
    slug: 'imlil',
    description: 'Hike into the foothills of Jbel Toubkal — Africa\'s highest peak — through Berber villages clinging to mountain slopes. The village of Imlil is a charming gateway to the High Atlas, with mule tracks, walnut orchards, and views that seem to belong to another era entirely.',
    short_description: 'Trek into Africa\'s highest mountain foothills through ancient Berber villages.',
    category: 'excursion',
    price: null,
    price_label: 'From €35 / person',
    duration: 'Full day (10 hrs)',
    cover_image_url: '/images/activities/imlil.jpg',
    gallery: [
      '/images/activities/imlil-g1.jpg',
      '/images/activities/imlil-g2.png',
    ],
    featured: false,
    order_rank: 6,
    highlights: ['Toubkal foothills trekking', 'Traditional Berber villages', 'Walnut & apple orchards', 'Mountain stream crossings', 'Local Berber lunch'],
    included: ['Transport', 'Guide', 'Lunch'],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'exc-7',
    title: 'Agadir & Paradise Valley',
    slug: 'agadir',
    description: 'Combine Agadir\'s stunning Atlantic beach with the hidden gem of Paradise Valley — a dramatic palm-lined gorge with emerald natural pools perfect for swimming. Stop at a traditional argan cooperative, browse Agadir\'s market, and end with fresh seafood on the seafront promenade.',
    short_description: 'Atlantic beach resort + hidden Paradise Valley gorge with natural swimming pools.',
    category: 'excursion',
    price: null,
    price_label: 'From €50 / person',
    duration: 'Full day (14 hrs)',
    cover_image_url: '/images/activities/agadir.jpg',
    gallery: [
      '/images/activities/agadir-g1.jpg',
      '/images/activities/agadir-g2.png',
    ],
    featured: false,
    order_rank: 7,
    highlights: ['Paradise Valley natural pools', 'Agadir beach', 'Argan cooperative visit', 'Atlantic seafood', 'Souk des Epices'],
    included: ['Transport', 'Guide', 'Argan cooperative visit'],
    created_at: '2024-01-01T00:00:00Z',
  },
]

// ─── TRANSPORT ROUTES ─────────────────────────────────────────────────────────
export const transportRoutes: TransportRoute[] = [
  {
    id: 'tr-1',
    type: 'airport_transfer',
    origin: 'Marrakech Menara Airport (RAK)',
    destination: 'Marrakech City / Medina / Hotels',
    price: null,
    price_label: 'From €15',
    notes: 'Meet & greet at arrivals. Name board provided. Available 24/7.',
    duration: '20–40 min',
  },
  {
    id: 'tr-2',
    type: 'airport_transfer',
    origin: 'Marrakech City / Medina / Hotels',
    destination: 'Marrakech Menara Airport (RAK)',
    price: null,
    price_label: 'From €15',
    notes: 'Flight monitoring. Driver adapts to delays at no extra cost.',
    duration: '20–40 min',
  },
  {
    id: 'tr-3',
    type: 'airport_transfer',
    origin: 'Casablanca Mohammed V Airport (CMN)',
    destination: 'Marrakech City',
    price: null,
    price_label: 'From €120',
    notes: 'Long-distance executive transfer. Wi-Fi & water included.',
    duration: '2.5–3 hrs',
  },
  {
    id: 'tr-4',
    type: 'point_to_point',
    origin: 'Marrakech',
    destination: 'Essaouira',
    price: null,
    price_label: 'From €60',
    notes: 'Direct private transfer. Drop-off at riad/hotel.',
    duration: '2.5 hrs',
  },
  {
    id: 'tr-5',
    type: 'point_to_point',
    origin: 'Marrakech',
    destination: 'Agadir',
    price: null,
    price_label: 'From €80',
    notes: 'Scenic Atlantic coastal route.',
    duration: '2.5 hrs',
  },
  {
    id: 'tr-6',
    type: 'point_to_point',
    origin: 'Marrakech',
    destination: 'Casablanca',
    price: null,
    price_label: 'From €100',
    notes: 'Comfortable executive vehicle. Refreshments included.',
    duration: '3–3.5 hrs',
  },
  {
    id: 'tr-7',
    type: 'point_to_point',
    origin: 'Marrakech',
    destination: 'Rabat',
    price: null,
    price_label: null,
    notes: 'Comfortable executive vehicle. Wi-Fi & water included.',
    duration: '3–3.5 hrs',
  },
]

// ─── REVIEWS ──────────────────────────────────────────────────────────────────
export const reviews: Review[] = [
  {
    id: 'rev-1',
    author_name: 'Sarah M.',
    rating: 5,
    text: 'The hot air balloon ride was absolutely magical — hands down the highlight of our trip to Morocco! The team was professional, punctual, and the Berber breakfast after landing was a lovely touch. Couldn\'t recommend Be Flex Travel more!',
    source: 'google',
    approved: true,
    created_at: '2024-03-15T00:00:00Z',
  },
  {
    id: 'rev-2',
    author_name: 'James & Lucy T.',
    rating: 5,
    text: 'Our 3-day Sahara tour was perfectly organised from start to finish. The desert camp under the stars was a once-in-a-lifetime experience. Mohamed was an exceptional guide — knowledgeable, friendly, and so passionate about his country.',
    source: 'google',
    approved: true,
    created_at: '2024-04-02T00:00:00Z',
  },
  {
    id: 'rev-3',
    author_name: 'Fatima K.',
    rating: 5,
    text: 'Booked the Ouarzazate day trip and it exceeded all expectations. The Aït Benhaddou kasbah was breathtaking and our guide knew all the best photo spots. The private car made everything so comfortable.',
    source: 'tripadvisor',
    approved: true,
    created_at: '2024-04-18T00:00:00Z',
  },
  {
    id: 'rev-4',
    author_name: 'Pierre L.',
    rating: 5,
    text: 'Le cours de cuisine était fantastique! We visited the spice market early morning (amazing atmosphere) then spent the afternoon cooking a full Moroccan feast. The instructor was patient, funny, and incredibly skilled. A must-do in Marrakech.',
    source: 'google',
    approved: true,
    created_at: '2024-05-07T00:00:00Z',
  },
  {
    id: 'rev-5',
    author_name: 'Emma R.',
    rating: 5,
    text: 'The sidecar tour was SO much fun — we laughed the entire time! Our driver took us through little alleys we\'d never have found alone and stopped for the most incredible mint tea. Perfect for couples!',
    source: 'site',
    approved: true,
    created_at: '2024-05-22T00:00:00Z',
  },
  {
    id: 'rev-6',
    author_name: 'David & Aisha N.',
    rating: 5,
    text: 'Used Be Flex Travel for our airport transfer and Ouzoud waterfalls day trip. Both were seamless. The waterfalls are incredible — the boat ride in the mist was unforgettable. Already planning to book the Sahara tour for next time!',
    source: 'google',
    approved: true,
    created_at: '2024-06-10T00:00:00Z',
  },
]

// ─── CIRCUIT 1: 2 JOURS — MARRAKECH / ZAGORA ─────────────────────────────────
export const circuit2DayZagora = {
  slug: '2-day-zagora',
  title: '2-Day Zagora Desert',
  subtitle: 'Marrakech → Draa Valley → Zagora → Marrakech',
  price_label: 'From €149 / person',
  duration: '2 days / 1 night',
  cover_image_url: '/images/activities/atlas-ouarzazate.jpg',
  short_description: 'A quick desert escape — cross the High Atlas, follow the ancient Draa Valley palmeraie, and sleep under the stars in a Zagora desert camp.',
  badge: '🌵 Quick Desert Fix',
  highlights_summary: ['Draa Valley palmeraie', 'Zagora desert camp', 'Camel sunset ride', 'Tamegroute library'],
  days: [
    {
      day: 1,
      title: 'Marrakech → Draa Valley → Zagora',
      subtitle: 'Crossing the High Atlas',
      description: 'Depart Marrakech at dawn and cross the majestic High Atlas via the Tizi n\'Tichka pass (2260m). Descend into the ochre Draa Valley — one of Morocco\'s longest and most beautiful valleys — lined with kasbahs, date palms, and ancient ksars. Stop at Agdz and Tamegroute (famous for its Islamic library). Arrive in Zagora in the afternoon. Mount your camel for a sunset ride into the dunes and spend the night in a comfortable desert camp under the stars.',
      highlights: ['Tizi n\'Tichka pass (2260m)', 'Draa Valley palmeraie', 'Agdz kasbah', 'Tamegroute library', 'Zagora sunset camel ride'],
      overnight: 'Desert Camp, Zagora',
    },
    {
      day: 2,
      title: 'Zagora → Marrakech',
      subtitle: 'Sunrise & Return',
      description: 'Rise before dawn to watch the desert sunrise paint the dunes in gold and crimson. After a traditional Berber breakfast at camp, begin the return journey through the Draa Valley, stopping at any sights missed on day one. Cross back over the High Atlas and return to Marrakech by late afternoon.',
      highlights: ['Sahara sunrise', 'Berber breakfast at camp', 'Draa Valley return', 'Atlas mountain panoramas'],
      overnight: null,
    },
  ],
  included: ['Private transport (A/C vehicle)', 'English-speaking guide', '1 night desert camp', 'Camel ride', 'Breakfast & dinner'],
  not_included: ['Lunches', 'Personal expenses', 'Travel insurance'],
}

// ─── CIRCUIT 2: 3 JOURS — MARRAKECH / DADES / MERZOUGA ───────────────────────
export const circuit3DayMerzouga = {
  slug: '3-day-merzouga',
  title: '3-Day Dades & Merzouga Sahara',
  subtitle: 'Marrakech → Boumalne Dades → Merzouga → Marrakech',
  price_label: 'From €199 / person',
  duration: '3 days / 2 nights',
  cover_image_url: '/images/activities/atlas-ouarzazate.jpg',
  short_description: 'The classic Sahara circuit — cross the High Atlas, sleep in the Dades Gorge, ride camels at sunrise in the legendary Erg Chebbi dunes.',
  badge: '🏜️ Most Popular',
  highlights_summary: ['Ait Benhaddou UNESCO', 'Dades Gorge', 'Erg Chebbi Dunes', 'Saharan stargazing'],
  days: [
    {
      day: 1,
      title: 'Marrakech → Ait Benhaddou → Dades',
      subtitle: 'High Atlas & Kasbahs',
      description: 'Depart Marrakech early and cross the spectacular High Atlas via the Tizi n\'Tichka pass. Visit the iconic UNESCO kasbah of Ait Benhaddou — filming location of Game of Thrones. Continue through Ouarzazate and the Valley of Roses to overnight in Boumalne Dades.',
      highlights: ['Tizi n\'Tichka pass (2260m)', 'Ait Benhaddou UNESCO Kasbah', 'Valley of Roses', 'Dades Gorge viewpoint'],
      overnight: 'Kasbah Hotel, Boumalne Dades',
    },
    {
      day: 2,
      title: 'Dades Gorge → Todra Gorge → Merzouga',
      subtitle: 'Into the Erg Chebbi Dunes',
      description: 'Explore the Dades Gorge\'s dramatic canyon walls, continue through the towering 300m walls of Todra Gorge, cross the pre-Saharan hamada, and arrive at Merzouga as the Erg Chebbi dunes glow amber. Sunset camel ride to your Berber camp under the Milky Way.',
      highlights: ['Todra Gorge (300m walls)', 'Erg Chebbi golden dunes', 'Camel trek to desert camp', 'Berber camp dinner', 'Stargazing'],
      overnight: 'Luxury Berber Desert Camp, Erg Chebbi',
    },
    {
      day: 3,
      title: 'Merzouga → Marrakech',
      subtitle: 'Sunrise Dunes & Return',
      description: 'Wake before dawn for a magical sunrise over the Sahara. Camel ride back, traditional Berber breakfast, then return through the Ziz Valley, Tafilalet Oasis, Middle Atlas forests, and back to Marrakech by evening.',
      highlights: ['Sahara sunrise on camelback', 'Ziz Valley oasis', 'Middle Atlas forests', 'Return to Marrakech'],
      overnight: null,
    },
  ],
  included: ['Private transport (A/C vehicle)', 'English-speaking guide', '2 nights accommodation', 'Camel trek', 'Breakfast & dinner daily', 'Ait Benhaddou entrance'],
  not_included: ['Lunches', 'Personal expenses', 'Travel insurance'],
}

// ─── CIRCUIT 3: 4 JOURS — MARRAKECH / DADES / MERZOUGA / OUARZAZATE ──────────
export const circuit4DayOuarzazate = {
  slug: '4-day-merzouga-ouarzazate',
  title: '4-Day Merzouga & Ouarzazate',
  subtitle: 'Marrakech → Dades → Merzouga → Ouarzazate → Marrakech',
  price_label: 'From €279 / person',
  duration: '4 days / 3 nights',
  cover_image_url: '/images/activities/ourika-valley.jpg',
  short_description: 'Desert dunes, dramatic gorges, and Hollywood kasbahs — the ultimate 4-day loop through southern Morocco\'s greatest landscapes.',
  badge: '🎬 Kasbahs & Sahara',
  highlights_summary: ['Erg Chebbi dunes', 'Ait Benhaddou', 'Todra Gorge', 'Ouarzazate studios'],
  days: [
    {
      day: 1,
      title: 'Marrakech → Ait Benhaddou → Dades',
      subtitle: 'High Atlas Crossing',
      description: 'Early departure crossing the High Atlas via Tizi n\'Tichka. Visit the UNESCO kasbah of Ait Benhaddou and explore Ouarzazate before continuing to Boumalne Dades for the night.',
      highlights: ['Tizi n\'Tichka pass', 'Ait Benhaddou UNESCO', 'Ouarzazate film city', 'Dades Valley arrival'],
      overnight: 'Kasbah Hotel, Boumalne Dades',
    },
    {
      day: 2,
      title: 'Dades → Todra Gorge → Merzouga',
      subtitle: 'Into the Great Erg',
      description: 'Explore the Dades Gorge, squeeze through the towering Todra Gorge, cross the hamada, and arrive at the legendary Erg Chebbi dunes for a sunset camel trek and night in the desert camp.',
      highlights: ['Dades Gorge walk', 'Todra Gorge (300m)', 'Erg Chebbi arrival', 'Sunset camel ride', 'Desert camp under stars'],
      overnight: 'Luxury Berber Camp, Erg Chebbi',
    },
    {
      day: 3,
      title: 'Merzouga → Sahara Day → Ouarzazate',
      subtitle: 'Full Sahara & Return West',
      description: 'Sunrise on the dunes, desert exploration — quad biking, nomad village visit, or pure silence. Return west through the Draa Valley and Ait Ben Haddou at golden hour. Overnight in Ouarzazate.',
      highlights: ['Sahara sunrise', 'Nomad village visit', 'Optional quad biking', 'Ait Benhaddou golden hour'],
      overnight: 'Hotel, Ouarzazate',
    },
    {
      day: 4,
      title: 'Ouarzazate → Marrakech',
      subtitle: 'Back Over the High Atlas',
      description: 'After breakfast, cross back over the High Atlas via Tizi n\'Tichka, stopping at a Berber village for tea and mountain views. Arrive back in Marrakech by early afternoon.',
      highlights: ['Tizi n\'Tichka mountain pass', 'Berber village tea stop', 'Atlas panoramas', 'Return to Marrakech'],
      overnight: null,
    },
  ],
  included: ['Private transport (A/C vehicle)', 'English-speaking guide', '3 nights accommodation', 'Camel trek', 'Breakfast & dinner daily', 'All entrance fees'],
  not_included: ['Lunches', 'Optional activities', 'Personal expenses', 'Travel insurance'],
}

// ─── CIRCUIT 4: 4 JOURS — MARRAKECH / DADES / MERZOUGA / FES / MARRAKECH ─────
export const circuit4DayFes = {
  slug: '4-day-merzouga-fes',
  title: '4-Day Merzouga & Fes Loop',
  subtitle: 'Marrakech → Dades → Merzouga → Fes → Marrakech',
  price_label: 'From €299 / person',
  duration: '4 days / 3 nights',
  cover_image_url: '/images/activities/agafay-desert.jpg',
  short_description: 'The Sahara-to-Imperial-City loop — cross the Atlas, sleep under desert stars, and discover the ancient medina of Fes before returning to Marrakech.',
  badge: '⭐ Sahara + Fes Loop',
  highlights_summary: ['Erg Chebbi Dunes', 'Fes UNESCO Medina', 'Todra Gorge', '3 nights included'],
  days: [
    {
      day: 1,
      title: 'Marrakech → Ait Benhaddou → Dades',
      subtitle: 'Atlas Crossing & Kasbahs',
      description: 'Depart at dawn, cross the High Atlas, visit Ait Benhaddou UNESCO kasbah, continue through the Valley of Roses to overnight in the Dades Valley.',
      highlights: ['Tizi n\'Tichka pass', 'Ait Benhaddou UNESCO', 'Valley of Roses', 'Dades Gorge'],
      overnight: 'Kasbah Hotel, Boumalne Dades',
    },
    {
      day: 2,
      title: 'Dades → Todra Gorge → Merzouga',
      subtitle: 'Into the Sahara',
      description: 'Morning in the Dades Gorge, through the dramatic Todra Gorge, across the hamada to the Erg Chebbi dunes. Sunset camel trek to your Berber desert camp.',
      highlights: ['Dades & Todra Gorges', 'Erg Chebbi golden dunes', 'Camel sunset ride', 'Milky Way stargazing'],
      overnight: 'Luxury Berber Camp, Erg Chebbi',
    },
    {
      day: 3,
      title: 'Merzouga → Ziz Valley → Fes',
      subtitle: 'Into the Imperial North',
      description: 'Sahara sunrise on camelback, then head north through the Ziz Valley, Tafilalet Oasis, and the cedar forests of the Middle Atlas. Arrive in Fes — Morocco\'s most complete medieval city — by evening.',
      highlights: ['Sahara sunrise', 'Ziz Valley oasis', 'Cedar forests & Barbary macaques', 'Arrival in Fes'],
      overnight: 'Riad, Fes Medina',
    },
    {
      day: 4,
      title: 'Fes → Marrakech',
      subtitle: 'Imperial City & Return',
      description: 'Morning exploring Fes — the Chouara tanneries, Al-Qarawiyyin university, souks and mosques. After lunch, drive south through the Middle Atlas back to Marrakech.',
      highlights: ['Fes medina UNESCO tour', 'Chouara Tannery', 'Al-Qarawiyyin University', 'Middle Atlas return'],
      overnight: null,
    },
  ],
  included: ['Private transport (A/C vehicle)', 'English-speaking guide', '3 nights accommodation (1 in desert camp)', 'Camel trek', 'Breakfast & dinner daily', 'All entrance fees'],
  not_included: ['Lunches', 'Personal expenses', 'Travel insurance'],
}

// ─── CIRCUIT 5: 6 JOURS — MARRAKECH / DADES / MERZOUGA / FES / CHEFCHAOUEN / TANGER ──
export const circuit6Day = {
  slug: '6-day-north',
  title: '6-Day Sahara to Tanger',
  subtitle: 'Marrakech → Dades → Merzouga → Fes → Chefchaouen → Tanger',
  price_label: 'From €449 / person',
  duration: '6 days / 5 nights',
  cover_image_url: '/images/activities/essaouira.jpg',
  short_description: 'From Saharan dunes to the blue city and the Strait of Gibraltar — a 6-day journey through Morocco\'s most iconic landscapes, ending in legendary Tanger.',
  badge: '🌊 Sahara to Sea',
  highlights_summary: ['Erg Chebbi Dunes', 'Fes Medina', 'Chefchaouen Blue City', 'Tanger & Gibraltar'],
  days: [
    {
      day: 1,
      title: 'Marrakech → Ait Benhaddou → Dades',
      subtitle: 'High Atlas Crossing',
      description: 'Early departure, cross the High Atlas via Tizi n\'Tichka, visit Ait Benhaddou UNESCO kasbah and Ouarzazate, continue to the Dades Valley.',
      highlights: ['Tizi n\'Tichka pass', 'Ait Benhaddou UNESCO', 'Draa Valley', 'Dades Gorge'],
      overnight: 'Kasbah Hotel, Boumalne Dades',
    },
    {
      day: 2,
      title: 'Dades → Todra → Merzouga',
      subtitle: 'Into the Great Erg',
      description: 'Through the Dades and Todra gorges, across the pre-Saharan hamada to the Erg Chebbi dunes. Sunset camel trek and night in a luxury Berber camp.',
      highlights: ['Dades & Todra Gorges', 'Erg Chebbi dunes', 'Camel sunset ride', 'Desert camp & stars'],
      overnight: 'Luxury Berber Camp, Erg Chebbi',
    },
    {
      day: 3,
      title: 'Merzouga → Ziz Valley → Fes',
      subtitle: 'Sahara Sunrise & North',
      description: 'Sunrise on the dunes, then north through the Ziz Valley, Tafilalet Oasis, cedar forests, and arrival in Fes — the spiritual heart of Morocco.',
      highlights: ['Sahara sunrise', 'Ziz Valley oasis', 'Cedar forests', 'Fes arrival'],
      overnight: 'Riad, Fes Medina',
    },
    {
      day: 4,
      title: 'Fes → Chefchaouen',
      subtitle: 'The Blue Pearl',
      description: 'Morning in the Fes medina — tanneries, souks, Al-Qarawiyyin university. Then head north to the magical blue-washed city of Chefchaouen in the Rif Mountains.',
      highlights: ['Fes Chouara Tannery', 'Al-Qarawiyyin', 'Chefchaouen blue medina', 'Rif mountain views'],
      overnight: 'Riad, Chefchaouen',
    },
    {
      day: 5,
      title: 'Chefchaouen → Tanger',
      subtitle: 'Across the North',
      description: 'Explore Chefchaouen\'s most photogenic corners in the morning, then drive north to legendary Tanger — gateway to Europe. Visit Cap Spartel, the Caves of Hercules, and Café Hafa overlooking the Strait of Gibraltar.',
      highlights: ['Chefchaouen old medina', 'Tanger medina', 'Cap Spartel & Caves of Hercules', 'Strait of Gibraltar views'],
      overnight: 'Hotel, Tanger',
    },
    {
      day: 6,
      title: 'Tanger — Free Morning',
      subtitle: 'The City at the Crossroads',
      description: 'A final morning to explore Tanger at leisure — the Kasbah museum, the Grand Socco, the Marshan and the legendary seafront. Return south or depart from Tanger.',
      highlights: ['Tanger Kasbah museum', 'Grand Socco market', 'Marshan gardens', 'Mediterranean & Atlantic junction'],
      overnight: null,
    },
  ],
  included: ['Private transport (A/C vehicle)', 'English-speaking guide', '5 nights accommodation (1 in desert camp)', 'Camel trek', 'Breakfast & dinner daily', 'All entrance fees'],
  not_included: ['Lunches', 'Personal expenses', 'Travel insurance'],
}

// ─── CIRCUIT 6: 10 JOURS ─────────────────────────────────────────────────────
export const circuit10Day = {
  slug: '10-day-grand-north',
  title: '10-Day Grand Northern Circuit',
  subtitle: 'Marrakech → Dades → Merzouga → Fes → Chefchaouen → Rabat → Casablanca → Marrakech',
  price_label: 'From €749 / person',
  duration: '10 days / 9 nights',
  cover_image_url: '/images/activities/agafay-desert.jpg',
  short_description: 'The complete Morocco loop — Sahara dunes, imperial cities, the blue city, Atlantic coasts and back. The grandest circuit through the kingdom.',
  badge: '👑 Grand North Circuit',
  highlights_summary: ['Erg Chebbi Sahara', 'Fes & Chefchaouen', 'Rabat Capital', 'Casablanca Hassan II', '9 nights'],
  days: [
    { day: 1, title: 'Marrakech → Ait Benhaddou → Dades', subtitle: 'High Atlas Crossing', description: 'Cross the High Atlas via Tizi n\'Tichka, visit the UNESCO kasbah of Ait Benhaddou and Ouarzazate, continue to the Dades Valley.', highlights: ['Tizi n\'Tichka pass', 'Ait Benhaddou UNESCO', 'Ouarzazate studios', 'Dades Gorge'], overnight: 'Kasbah Hotel, Boumalne Dades' },
    { day: 2, title: 'Dades → Todra Gorge → Merzouga', subtitle: 'Into the Sahara', description: 'Through the dramatic gorges and across the hamada to the Erg Chebbi dunes. Camel sunset ride and luxury desert camp.', highlights: ['Dades & Todra Gorges', 'Erg Chebbi dunes', 'Camel sunset ride', 'Desert camp'], overnight: 'Luxury Berber Camp, Erg Chebbi' },
    { day: 3, title: 'Merzouga — Full Sahara Day', subtitle: 'Desert Freedom', description: 'Sunrise dunes, camel riding, nomad village visit, optional quad biking, and a second magical night under the Milky Way.', highlights: ['Sahara sunrise', 'Camel trekking', 'Nomad family visit', 'Quad biking (optional)', 'Stargazing night 2'], overnight: 'Luxury Berber Camp, Erg Chebbi' },
    { day: 4, title: 'Merzouga → Ziz Valley → Fes', subtitle: 'Into the Imperial North', description: 'Head north through the Ziz Valley, Tafilalet Oasis, and the cedar forests of the Middle Atlas, arriving in Fes by evening.', highlights: ['Ziz Valley oasis', 'Tafilalet palmeraie', 'Cedar forests & macaques', 'Fes arrival'], overnight: 'Riad, Fes Medina' },
    { day: 5, title: 'Fes Medina — Full Day', subtitle: 'The Soul of Morocco', description: 'A full day in Fes el-Bali — the tanneries, Al-Qarawiyyin university, Medersa Bou Inania, and the ancient souks.', highlights: ['Chouara Tannery', 'Al-Qarawiyyin University', 'Medersa Bou Inania', 'Ancient souks'], overnight: 'Riad, Fes Medina' },
    { day: 6, title: 'Fes → Chefchaouen', subtitle: 'The Blue Pearl of the Rif', description: 'Drive north through rolling Rif hills to the magical blue-washed medina of Chefchaouen.', highlights: ['Rif mountain scenery', 'Chefchaouen blue medina', 'Ras el-Maa waterfall', 'Mint tea in the plaza'], overnight: 'Riad, Chefchaouen' },
    { day: 7, title: 'Chefchaouen → Rabat', subtitle: 'To the Atlantic Capital', description: 'Morning in Chefchaouen, then drive along the Atlantic coast to Rabat. Visit the Kasbah des Oudaias and the Hassan Tower.', highlights: ['Chefchaouen final wander', 'Kasbah des Oudaias', 'Hassan Tower', 'Chellah necropolis'], overnight: 'Hotel, Rabat' },
    { day: 8, title: 'Rabat → Casablanca', subtitle: 'Capital to Modern Metropolis', description: 'Explore Rabat in the morning, then drive to Casablanca. Visit the extraordinary Hassan II Mosque.', highlights: ['Rabat Royal Palace area', 'Casablanca Hassan II Mosque', 'Corniche seafront', 'Art Deco architecture'], overnight: 'Hotel, Casablanca' },
    { day: 9, title: 'Casablanca → Marrakech', subtitle: 'Return to the South', description: 'Final Casablanca morning, then drive south back to Marrakech, arriving by midday.', highlights: ['Casablanca old medina', 'Central Market', 'Atlantic views', 'Return to Marrakech'], overnight: 'Hotel, Marrakech' },
    { day: 10, title: 'Marrakech — Free Day', subtitle: 'The Pink City at Your Pace', description: 'Relax in Marrakech — the Majorelle Garden, Jemaa el-Fna, the souks, or a final hammam.', highlights: ['Majorelle Garden', 'Jemaa el-Fna square', 'Marrakech souks', 'Final hammam'], overnight: null },
  ],
  included: ['Private transport (A/C vehicle)', 'English-speaking guide', '9 nights accommodation (2 in desert camp)', 'Camel treks (x2)', 'Breakfast & dinner daily', 'All entrance fees'],
  not_included: ['Lunches', 'Optional activities', 'Personal expenses', 'Travel insurance'],
}

// ─── CIRCUIT 7: 20 JOURS — LE GRAND TOUR DU MAROC ────────────────────────────
export const circuit20Day = {
  slug: '20-day-grand-tour',
  title: '20-Day Grand Tour du Maroc',
  subtitle: 'Marrakech → Sahara → Zagora → Agadir → Fes → Chefchaouen → Tanger → Rabat → Casablanca → Marrakech',
  price_label: 'From €1,499 / person',
  duration: '20 days / 19 nights',
  cover_image_url: '/images/activities/ouzoud-waterfalls.jpg',
  short_description: 'The ultimate Morocco experience — every imperial city, both Saharan deserts, the Atlantic and Mediterranean coasts, mountain passes and ancient medinas. Nothing is left unseen.',
  badge: '🇲🇦 Le Grand Tour',
  highlights_summary: ['Both Sahara deserts', '4 Imperial Cities', 'Chefchaouen & Tanger', 'Atlantic & Mediterranean', 'Complete Morocco'],
  days: [
    { day: 1, title: 'Marrakech — Arrival & Orientation', subtitle: 'The Pink City', description: 'Arrive in Marrakech. Explore the Jemaa el-Fna square, the souks, and the Koutoubia Mosque. Welcome dinner in the medina.', highlights: ['Jemaa el-Fna square', 'Marrakech souks', 'Koutoubia Mosque', 'Welcome dinner'], overnight: 'Riad, Marrakech Medina' },
    { day: 2, title: 'Marrakech — Full City Day', subtitle: 'Palaces, Gardens & Hammam', description: 'Full day discovering Marrakech — the Bahia Palace, Saadian Tombs, Majorelle Garden, and an evening hammam.', highlights: ['Bahia Palace', 'Saadian Tombs', 'Majorelle Garden', 'Traditional hammam'], overnight: 'Riad, Marrakech Medina' },
    { day: 3, title: 'Marrakech → Essaouira', subtitle: 'Atlantic Coast & Blue City', description: 'Day trip to the magical walled city of Essaouira — UNESCO medina, ocean ramparts, Gnawa music, and fresh Atlantic seafood.', highlights: ['Essaouira UNESCO medina', 'Ocean ramparts', 'Argan cooperative', 'Fresh Atlantic seafood'], overnight: 'Riad, Marrakech' },
    { day: 4, title: 'Marrakech → Ait Benhaddou → Ouarzazate', subtitle: 'High Atlas & Kasbahs', description: 'Cross the High Atlas via Tizi n\'Tichka (2260m), visit Ait Benhaddou UNESCO kasbah, overnight in Ouarzazate.', highlights: ['Tizi n\'Tichka pass', 'Ait Benhaddou UNESCO', 'Draa Valley palmeraie', 'Ouarzazate film studios'], overnight: 'Hotel, Ouarzazate' },
    { day: 5, title: 'Ouarzazate → Valley of Roses → Dades', subtitle: 'Roses & Canyon Country', description: 'Visit the Valley of Roses, explore the dramatic Dades Gorge, and relax in a kasbah hotel.', highlights: ['Valley of Roses', 'Kelaat M\'gouna rosewater', 'Dades Gorge walk', 'Atlas sunset'], overnight: 'Kasbah Hotel, Boumalne Dades' },
    { day: 6, title: 'Dades → Todra Gorge → Merzouga', subtitle: 'Into the Great Erg', description: 'Through the towering Todra Gorge, across the hamada, arriving at the Erg Chebbi dunes for sunset camel ride.', highlights: ['Todra Gorge (300m walls)', 'Erg Chebbi arrival', 'Sunset camel trek', 'Desert camp'], overnight: 'Luxury Berber Camp, Erg Chebbi' },
    { day: 7, title: 'Merzouga — Full Sahara Day', subtitle: 'Desert Without Limits', description: 'Sunrise dunes, camel riding, nomad family visit, quad biking, desert music by the fire. Second night under the Milky Way.', highlights: ['Sahara sunrise', 'Camel trekking', 'Nomad family visit', 'Quad biking', 'Milky Way stargazing'], overnight: 'Luxury Berber Camp, Erg Chebbi' },
    { day: 8, title: 'Merzouga → Zagora Desert', subtitle: 'Two Deserts in One Trip', description: 'Drive south through the Draa Valley to discover the Zagora desert — ancient ksar and vast stony erg.', highlights: ['Draa Valley palmeraie', 'Tamegroute library', 'Zagora ksar', 'Desert camp'], overnight: 'Desert Camp, Zagora' },
    { day: 9, title: 'Zagora → Agadir', subtitle: 'Atlantic Beach & Paradise Valley', description: 'Drive west through the Anti-Atlas to Agadir. Visit the hidden Paradise Valley gorge with emerald natural pools.', highlights: ['Anti-Atlas crossing', 'Paradise Valley natural pools', 'Agadir beach promenade', 'Atlantic seafood'], overnight: 'Hotel, Agadir' },
    { day: 10, title: 'Agadir → Marrakech', subtitle: 'Return to the Red City', description: 'Morning in Agadir — Kasbah ruins with Atlantic panoramas. Drive back to Marrakech along the Atlantic coastal route.', highlights: ['Agadir Kasbah panoramas', 'Souk market', 'Atlantic coastal road', 'Marrakech return'], overnight: 'Riad, Marrakech' },
    { day: 11, title: 'Marrakech → Ouzoud Waterfalls', subtitle: 'Morocco\'s Highest Falls', description: 'Day trip to the spectacular 110m Ouzoud Waterfalls. Swim in natural pools, spot wild Barbary macaques.', highlights: ['Ouzoud 110m waterfall', 'Wild Barbary macaques', 'Boat ride in the mist', 'Natural swimming pools'], overnight: 'Riad, Marrakech' },
    { day: 12, title: 'Marrakech → Fes', subtitle: 'Through the Middle Atlas', description: 'Drive north through the Middle Atlas — Beni Mellal, Ifrane, cedar forests — arriving in Fes by evening.', highlights: ['Middle Atlas forests', 'Ifrane town', 'Cedar forests & macaques', 'Fes arrival'], overnight: 'Riad, Fes Medina' },
    { day: 13, title: 'Fes — Full Medina Day', subtitle: 'The Soul of Morocco', description: 'An entire day in Fes el-Bali — the Chouara tanneries, Al-Qarawiyyin (world\'s oldest university), Medersa Bou Inania, spice market.', highlights: ['Chouara Tannery', 'Al-Qarawiyyin University', 'Medersa Bou Inania', 'Fes spice market'], overnight: 'Riad, Fes Medina' },
    { day: 14, title: 'Fes → Chefchaouen', subtitle: 'The Blue Pearl', description: 'Head north through the Rif Mountains to the mesmerising blue-washed medina of Chefchaouen.', highlights: ['Rif mountain drive', 'Chefchaouen blue medina', 'Ras el-Maa waterfall', 'Plaza Uta el-Hammam'], overnight: 'Riad, Chefchaouen' },
    { day: 15, title: 'Chefchaouen — Full Day', subtitle: 'Blue Streets & Mountain Air', description: 'A full unhurried day in Chefchaouen — hike to the Spanish mosque, Kasbah museum, blue alleys, mountain cuisine.', highlights: ['Spanish Mosque sunset hike', 'Kasbah museum', 'Blue medina photography', 'Mountain cuisine'], overnight: 'Riad, Chefchaouen' },
    { day: 16, title: 'Chefchaouen → Tanger', subtitle: 'Gateway to Europe', description: 'Drive north to legendary Tanger. Visit Cap Spartel, the Caves of Hercules, the Kasbah, and Cafe Hafa.', highlights: ['Cap Spartel lighthouse', 'Caves of Hercules', 'Tanger Kasbah', 'Strait of Gibraltar views'], overnight: 'Hotel, Tanger' },
    { day: 17, title: 'Tanger → Rabat', subtitle: 'Along the Atlantic', description: 'Drive south along the Atlantic coast through Asilah to Rabat. Visit the Kasbah des Oudaias and Hassan Tower.', highlights: ['Asilah whitewashed medina', 'Kasbah des Oudaias', 'Hassan Tower', 'Chellah necropolis'], overnight: 'Hotel, Rabat' },
    { day: 18, title: 'Rabat → Casablanca', subtitle: 'Capital to Modern Metropolis', description: 'Explore Rabat, then drive to Casablanca. Visit the awe-inspiring Hassan II Mosque.', highlights: ['Mausoleum of Mohammed V', 'Rabat medina', 'Casablanca Hassan II Mosque', 'Corniche seafront'], overnight: 'Hotel, Casablanca' },
    { day: 19, title: 'Casablanca → Marrakech', subtitle: 'Return to the South', description: 'Final Casablanca morning — old Medina, Central Market, or seafront. Drive south back to Marrakech.', highlights: ['Casablanca Art Deco buildings', 'Old Medina market', 'Atlantic farewell', 'Marrakech return'], overnight: 'Riad, Marrakech' },
    { day: 20, title: 'Marrakech — Grand Finale', subtitle: 'The End of the Road', description: 'A final day in Marrakech — last shopping, rooftop lunch, Jemaa el-Fna evening. Your Grand Tour du Maroc is complete.', highlights: ['Marrakech souks farewell', 'Rooftop lunch with Atlas views', 'Jemaa el-Fna final evening', 'Celebratory dinner'], overnight: null },
  ],
  included: ['Private transport (A/C vehicle) throughout', 'Expert English-speaking guide', '19 nights accommodation (2 nights desert camp, rest in riads/hotels)', 'Camel treks (x3)', 'Breakfast & dinner daily', 'All entrance fees & activities listed'],
  not_included: ['Lunches', 'Optional activities (quad biking, etc.)', 'Personal expenses', 'International flights', 'Travel insurance'],
}

// ─── ALL CIRCUITS (for listing page) ─────────────────────────────────────────
export const circuits = [
  circuit2DayZagora,
  circuit3DayMerzouga,
  circuit4DayOuarzazate,
  circuit4DayFes,
  circuit6Day,
  circuit10Day,
  circuit20Day,
]

// Legacy exports for backward compatibility
export const saharaTour = circuit3DayMerzouga
export const saharaTour5Day = circuit6Day
export const saharaTour7Day = circuit10Day
